eureka.instance.hostname: localhost
eureka.client.service-url.defaultZone: http://localhost:8761/eureka

server.port: 8090

spring.application.name: students
spring.config.import: optional:configserver:http://localhost:8888
spring.datasource: driver-class-name: org.mysql.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/test
spring.datasource.username: root
spring.datasource.password: 1234